import { Pressable, StyleSheet, Text, View } from 'react-native';
import { CoachInsight } from '../types';
import { radii, ThemeColors } from '../theme';
import { useThemedStyles } from '../theme/ThemeProvider';

const categoryLabel = { balance: 'Denge', speed_accuracy: 'Tempo', schedule: 'Plan', recovery: 'Toparlanma' } as const;
export function PersonalCoachCard({ insight, busy, onApply, onDismiss }: { insight: CoachInsight; busy?: boolean; onApply: () => void; onDismiss: () => void }) {
  const styles = useThemedStyles(createStyles);
  return <View style={styles.card}><View style={styles.accent} /><View style={styles.content}><View style={styles.header}><Text style={styles.badge}>◈ KOÇUN NOTU</Text><Text style={styles.category}>{categoryLabel[insight.category]}</Text></View><Text style={styles.insight} numberOfLines={3}>{insight.insightText}</Text><Text style={styles.recommendation}>{insight.recommendedActionText}</Text><View style={styles.actions}><Pressable disabled={busy} onPress={onApply} style={styles.apply}><Text style={styles.applyText}>{busy ? 'Uygulanıyor…' : 'Öneriyi Uygula'}</Text></Pressable><Pressable disabled={busy} onPress={onDismiss} style={styles.dismiss}><Text style={styles.dismissText}>Şimdilik Gizle</Text></Pressable></View></View></View>;
}
const createStyles = (colors: ThemeColors) => StyleSheet.create({ card: { flexDirection: 'row', overflow: 'hidden', marginBottom: 12, borderRadius: radii.card, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, accent: { width: 4, backgroundColor: colors.coachAccent }, content: { flex: 1, padding: 14 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, badge: { color: colors.coachAccent, fontSize: 9, fontWeight: '900', letterSpacing: 1 }, category: { color: colors.textMuted, fontSize: 9, fontWeight: '700' }, insight: { color: colors.textPrimary, fontSize: 13, lineHeight: 19, fontWeight: '600', marginTop: 9 }, recommendation: { color: colors.textMuted, fontSize: 10, lineHeight: 15, marginTop: 5 }, actions: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12 }, apply: { paddingHorizontal: 13, paddingVertical: 9, borderRadius: radii.pill, backgroundColor: colors.coachAccent }, applyText: { color: colors.onAccent, fontSize: 10, fontWeight: '800' }, dismiss: { paddingHorizontal: 9, paddingVertical: 9 }, dismissText: { color: colors.textMuted, fontSize: 10, fontWeight: '700' } });
